karma:
  refresh:
    five-cron: 1 0/5 * * * *
    fifteen-cron: 1 0/15 * * * *
  okx:
    host: https://www.okx.com
  telegram:
    host: https://api.telegram.org
    bot-token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}
  rule-reminder:
    cron: 0 0 0/6 * * *

spring:
  application:
    name: karma

  r2dbc:
    name: sa
    password: password
