karma:
  okx:
    host: https://www.okx.com
  telegram:
    host: https://api.telegram.org
    bot-token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}

spring:
  application:
    name: karma

  r2dbc:
    name: sa
    password: password
